apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: codeql-webgoat
spec:
  description: | 
    This pipeline clones a git repo, then analyses it with CodeQL.
  params:
  - name: build-image
    type: string
    description: The image to use for building the project.
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  - name: ref
    type: string
    description: The git ref to check out.
    default: "refs/heads/main"
  - name: source-path-dir
    type: string
    description: The path to the source code directory, relative to the checked out repository root.
    default: ""
  - name: codeql-language
    type: string
    description: The language to analyse.
  - name: codeql-build-command
    type: string
    description: The command to build the project.
    default: ""
  - name: codeql-query-suite
    type: string
    description: The query suite to use.
    default: $(params.codeql-language)-security-extended
  - name: codeql-extra-args
    type: string
    description: Extra arguments to pass to the CodeQL CLI.
    default: ""
  workspaces:
  - name: shared-data
    description: This workspace contains the cloned repo files, so they can be read by the next task.
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.ref)
  - name: codeql
    runAfter: ["git-clone"]
    taskRef:
      name: codeql
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: build-image
      value: $(params.build-image)
    - name: repo-url
      value: $(params.repo-url)  
    - name: ref
      value: $(params.ref)
    - name: commit-sha
      value: $(tasks.git-clone.results.commit)
    - name: source-path-dir
      value: $(params.source-path-dir)
    - name: codeql-language
      value: $(params.codeql-language)
    - name: codeql-build-command
      value: $(params.codeql-build-command)
    - name: codeql-query-suite
      value: $(params.codeql-query-suite)
    - name: codeql-extra-args
      value: $(params.codeql-extra-args)
